Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -21,10 +21,10 @@ jobs:
           version_name: version
           method: curl
           timeout: 5 
-    - run: |
-        exit-status="$?"
-        echo "exit_stataus=$exit-status" >> $GITHUB_OUTPUT
-      if: failure()
+          run: echo "exit_stataus=$?" >> $GITHUB_OUTPUT
+#     - run: |
+#         echo "exit_stataus=$exit-status" >> $GITHUB_OUTPUT
+#       if: failure()
           
 #   notification:
 #     runs-on: ubuntu-latest
